### ISSUE TITLE
Backend Tests

### ISSUE THREAD

**Issue by lTimeless** [SmartHub-Io/SmartHub#35]
Add some backend Tests so we have a higher test coverage.

-> Add some Unittests
-> Add some Integrationtests

[AB#154](https://dev.azure.com/SmartHub-Studio/58c1ce45-66da-4da5-92ef-f13f0440b4ac/_workitems/edit/154)

[AB#158](https://dev.azure.com/SmartHub-Studio/58c1ce45-66da-4da5-92ef-f13f0440b4ac/_workitems/edit/158)

**Comment by ArtemK123** [comment]
Hi, 
I would like to add some tests.
As far as I can see, you haven`t added any yet, so the whole infrastructure should be set up.

I am going to use xUnit as a test framework and NSubstitute for isolation and mocks in unit tests.
If you have any comments - feel free to write to me.

Also, could you please assign the issue to me?

**Comment by lTimeless** [comment]
@ArtemK123 Nice :)  it is assigned to you now.
No there are no tests yet and use whatever you want ;) 

Just structure the tests appropriately.

**Comment by ArtemK123** [comment]
https://github.com/SmartHub-Io/SmartHub/pull/42

**Comment by lTimeless** [comment]
Merged into develop
