### ISSUE TITLE
123 warnings

### ISSUE THREAD

**Issue by ArtemK123** [SmartHub-Io/SmartHub#41]
**Brief Descrition**
Hi,
I have just cloned the solution and after the first fresh build I had 123 warnings. Most of them are related to possible nullability, but there are also other causes.  

**How to reproduce**
Clone the repo and run the build. I used the dotnet CLI tool in order to have only MsBuild warnings and do not involve IDE code styles.

**Expected Behavior**
0 warnings :)
I think it will help contributors to be sure that their pull request is reliable and will not break anything

**Actual Behavior**
123 warnings

**Specifications**
  - Version: development branch
  - Platform: Windows -> .Net Core 5.0 rc2
  - Subsystem:

**ScreenShots** (Optional)
![image](https://user-images.githubusercontent.com/31692671/96754069-76fc2880-13d9-11eb-997f-3d1916ae5df2.png)

[AB#157](https://dev.azure.com/SmartHub-Studio/58c1ce45-66da-4da5-92ef-f13f0440b4ac/_workitems/edit/157)

**Comment by lTimeless** [comment]
Thanks that's on my bucketlist for a while now 😅🙈

If you can fix some, feel free to do so. But you do not have to do it :)

**Comment by ArtemK123** [comment]
I will try to fix all of them.

Just tell me please about Hacktoberfest policies in your repo. Should you or I label somehow the issue or pull request in order to make it count in Hacktoberfest?

**Comment by lTimeless** [comment]
Wow okay that would be relly nice. Could you do them in a seperate PR ?

I labeled the PRs and issues now with the "hacktoberfest" labeles

**Comment by ArtemK123** [comment]
https://github.com/SmartHub-Io/SmartHub/pull/43
